AikoWeb/WebApplication/Models/Equipment.cs
using System;
using System.ComponentModel;

namespace WebApplication.Models
{
    public class Equipment
    {
        [DisplayName("ID")]
        public Guid Id { get; set; }
        
        [DisplayName("Equipment Model")]
        public EquipmentModel EquipmentModel { get; set; }
        
        [DisplayName("Equipment")]
        public string Name { get; set; }
    }
}

AikoWeb/WebApplication/Models/EquipmentModel.cs
using System;
using System.ComponentModel;

namespace WebApplication.Models
{
    public class EquipmentModel
    {
        [DisplayName("Equipment Model ID")]
        public Guid Id { get; set; }
        
        [DisplayName("Equipment Model")]
        public string Name { get; set; }
    }
}

AikoWeb/WebApplication/Models/EquipmentState.cs
using System;

namespace WebApplication.Models
{
    public class EquipmentState
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        public string Color { get; set; }
    }
}

AikoWeb/WebApplication/Models/EquipmentStateHistory.cs
using System;

namespace WebApplication.Models
{
    public class EquipmentStateHistory
    {
        public DateTime Date { get; set; }
        
        public Equipment Equipment { get; set; }
        
        public EquipmentState EquipmentState { get; set; }

    }
}

AikoWeb/WebApplication/Models/ViewModel/EquipmentViewModel.cs
using System.Collections.Generic;

namespace WebApplication.Models.ViewModel
{
    public class EquipmentViewModel : LayoutViewModel<EquipmentViewModel>
    {
        public IEnumerable<Equipment> Equipments { get; set; }

        public EquipmentViewModel()
        {
            ViewTitle = "Equipments";
        }
    }
}

AikoWeb/WebApplication/Models/ViewModel/ErrorViewModel.cs
using System;

namespace WebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AikoWeb/WebApplication/Models/ViewModel/HomeViewModel.cs
using System.Collections.Generic;

namespace WebApplication.Models.ViewModel
{
    public class HomeViewModel : LayoutViewModel<EquipmentStateHistoryViewModel>
    {
        public HomeViewModel()
        {
            ViewTitle = "Equipment State History";
        }
    }
}

AikoWeb/WebApplication/Models/ViewModel/LayoutViewModel.cs
namespace WebApplication.Models.ViewModel
{
    public class LayoutViewModel
    {
        public string ViewTitle => "Aiko Digital";

    }
    
    public class LayoutViewModel<T> : LayoutViewModel
    {
        public string ViewTitle { get; set; }
        
        public T PageModel { get; }
        
        public LayoutViewModel(T pageModel)
        {
            PageModel = pageModel;
        }

        protected LayoutViewModel()
        {
        }
    }
}

AikoWeb/WebApplication/Models/ViewModel/StateViewModel.cs
using System.Collections.Generic;

namespace WebApplication.Models.ViewModel
{
    public class EquipmentStateHistoryViewModel : LayoutViewModel<EquipmentStateHistoryViewModel>
    {
        public IEnumerable<EquipmentStateHistory> EquipmentHistories { get; set; }

        public EquipmentStateHistoryViewModel()
        {
            ViewTitle = "Equipment State History";
        }
    }
}

AikoWeb/WebApplication/Controllers/EquipmentsController.cs
using System.Collections.Generic;
using System.Net.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebApplication.Generics;
using WebApplication.Models;
using WebApplication.Models.ViewModel;

namespace WebApplication.Controllers
{
    public class EquipmentsController : Controller
    {
        public IActionResult Index()
        {
            var _request = new ApiRequest(new HttpClient());
            var responseContent = _request.GetAsync("equipment").Result;
            var model = JsonConvert.DeserializeObject<List<Equipment>>(responseContent);
            return View(new LayoutViewModel<EquipmentViewModel>(new EquipmentViewModel
            {
                Equipments = model
            }));
        }
        
    }
}

AikoWeb/WebApplication/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Net.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebApplication.Generics;
using WebApplication.Models;
using WebApplication.Models.ViewModel;

namespace WebApplication.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            var model = new LayoutViewModel<HomeViewModel>(new HomeViewModel());
            return View(model);
        }
        
        // [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        // public IActionResult Error()
        // {
            // return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        // }
    }
}

AikoWeb/WebApplication/Controllers/StateController.cs
using System.Collections.Generic;
using System.Net.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebApplication.Generics;
using WebApplication.Models;
using WebApplication.Models.ViewModel;

namespace WebApplication.Controllers
{
    public class StateController : Controller
    {
        public IActionResult EquipmentStateHistory()
        {
            var _request = new ApiRequest(new HttpClient());
            var responseContent = _request.GetAsync("EquipmentStateHistory").Result;
            var model = JsonConvert.DeserializeObject<List<EquipmentStateHistory>>(responseContent);
            return View(new LayoutViewModel<EquipmentStateHistoryViewModel>(new EquipmentStateHistoryViewModel
            {
                EquipmentHistories = model
            }));
        }
    }
}

AikoWeb/WebApplication/Views/Equipments/Index.cshtml
@model WebApplication.Models.ViewModel.LayoutViewModel<WebApplication.Models.ViewModel.EquipmentViewModel>

<div class="">
    <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
        <ol class="breadcrumb bg-white">
            <li class="breadcrumb-item">
                <a asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">@Model.PageModel.ViewTitle</li>
        </ol>
    </nav>
    <table class="table table-striped table-hover table-responsive text-center">
        <thead>
        <tr>
            <th >@Html.DisplayNameFor(x => x.PageModel.Equipments.First().Id)</th>
            <th >@Html.DisplayNameFor(x => x.PageModel.Equipments.First().Name)</th>
            <th >@Html.DisplayNameFor(x => x.PageModel.Equipments.First().EquipmentModel.Name)</th>
            <th >@Html.DisplayNameFor(x => x.PageModel.Equipments.First().EquipmentModel.Id)</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var equipment in Model.PageModel.Equipments)
        {
            <tr>
                <td >@Html.DisplayFor(x => equipment.Id)</td>
                <td >@Html.DisplayFor(x => equipment.Name)</td>
                <td >@Html.DisplayFor(x => equipment.EquipmentModel.Name)</td>
                <td >@Html.DisplayFor(x => equipment.EquipmentModel.Id)</td>
            </tr>
        }
        </tbody>
    </table>
</div>

AikoWeb/WebApplication/Views/Shared/_Layout.cshtml
@model WebApplication.Models.ViewModel.LayoutViewModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@Model.ViewTitle - WebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/global.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/logo.png" alt="" class="aiko-logo-size"/>
            </a>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Equipments" asp-action="Index">Equipments</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="State" asp-action="EquipmentStateHistory">Equipment Histories</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container text-center">
        &copy; 2021 - Aiko Dev Test - WebApplication
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>