AikoFrontEnd/Models/Equipment.cs
using System;

namespace AikoFrontEnd.Models
{
    public class Equipment
    { 
        public Guid Id { get; set; }
        
        public Guid EquipmentModelId { get; set; }
        
        public String Name { get; set; }

        public EquipmentModel EquipmentModel { get; set; }
    }
}

AikoFrontEnd/Models/EquipmentHourlyEarnings.cs
using System;

namespace AikoFrontEnd.Models
{
    public class EquipmentHourlyEarnings
    {
        public Guid EquipmentModelId { get; set; }
        public Guid EquipmentStateId { get; set; }
        public Double Value { get; set; }
    }
}

AikoFrontEnd/Models/EquipmentModel.cs
using System;

namespace AikoFrontEnd.Models
{   
    public class EquipmentModel
    {
        public Guid Id { get; set; }
        public String Name { get; set; }
    }
}

AikoFrontEnd/Models/EquipmentPositionHistory.cs
using System;

namespace AikoFrontEnd.Models
{
    public class EquipmentPositionHistory
    {
        public Guid EquipmentId { get; set; }
        public DateTime Date { get; set; }
        public Double Lat { get; set; }
        public Double Lon { get; set; }

        public Equipment Equipment { get; set; }
    }
}

AikoFrontEnd/Models/EquipmentState.cs
using System;

namespace AikoFrontEnd.Models
{
    public class EquipmentState
    {
        public Guid Id { get; set; }
        public String Name { get; set; }
        public String Color { get; set; }
    }
}

AikoFrontEnd/Models/EquipmentStateHistory.cs
using System;

namespace AikoFrontEnd.Models
{
    public class EquipmentStateHistory
    {
        public Guid EquipmentId { get; set; }
        public DateTime Date { get; set; }
        public Guid EquipmentStateId { get; set; }

        public Equipment Equipment { get; set; }
    }
}

AikoFrontEnd/Pages/Configs.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AikoFrontEnd.Pages
{
    public class ConfigsModel : PageModel
    {
        private readonly ILogger<ConfigsModel> _logger;

        public ConfigsModel(ILogger<ConfigsModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

AikoFrontEnd/Pages/EquipmentPositionHistoryPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;
using models = AikoFrontEnd.Models;

namespace AikoFrontEnd.Pages
{
    public class EquipmentPositionHistoryPage : PageModel
    {
        public List<models.EquipmentPositionHistory> currentPositions { get; set; }
        
        private readonly ILogger<EquipmentPositionHistoryPage> _logger;

        public EquipmentPositionHistoryPage(ILogger<EquipmentPositionHistoryPage> logger)
        {
            _logger = logger;
        }

        public async Task OnGet(Guid equipmentId)
        {
            using (var client = new HttpClient())
            {
                var responseHist = await client.GetAsync(
                    "https://localhost:5001/api/EquipmentPositionHistories/currentPosition");
                responseHist.EnsureSuccessStatusCode();
                
                currentPositions = JsonConvert.DeserializeObject<List<models.EquipmentPositionHistory>>(responseHist.Content.ReadAsStringAsync().Result);
            }
        }
    }
}

AikoFrontEnd/Pages/EquipmentStateHistoryPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;
using models = AikoFrontEnd.Models;

namespace AikoFrontEnd.Pages
{
    public class EquipmentStateHistoryPage : PageModel
    {
        public List<models.EquipmentState> states { get; set; }
        public List<models.EquipmentStateHistory> currentStates { get; set; }
        public List<models.EquipmentStateHistory> equipmentHistory { get; set; }
        
        private readonly ILogger<EquipmentStateHistoryPage> _logger;

        public EquipmentStateHistoryPage(ILogger<EquipmentStateHistoryPage> logger)
        {
            _logger = logger;
        }

        public async Task OnGet(Guid equipmentId)
        {
            using (var client = new HttpClient())
            {
                var responseStates = await client.GetAsync(
                    "https://localhost:5001/api/EquipmentStates");
                responseStates.EnsureSuccessStatusCode();
                states = JsonConvert.DeserializeObject<List<models.EquipmentState>>(responseStates.Content.ReadAsStringAsync().Result);

                var responseHist = await client.GetAsync(
                    "https://localhost:5001/api/EquipmentStateHistories/currentState");
                responseHist.EnsureSuccessStatusCode();
                
                currentStates = JsonConvert.DeserializeObject<List<models.EquipmentStateHistory>>(responseHist.Content.ReadAsStringAsync().Result);

                if (equipmentId != Guid.Empty)
                {
                    Console.WriteLine(equipmentId);
                    var responseHistComplete = await client.GetAsync(
                        $"https://localhost:5001/api/EquipmentStateHistories/{equipmentId}");
                    responseHistComplete.EnsureSuccessStatusCode();
                    equipmentHistory = JsonConvert.DeserializeObject<List<models.EquipmentStateHistory>>(responseHistComplete.Content.ReadAsStringAsync().Result);
                }
            }
        }

        public IActionResult OnPostEquip(Guid equipmentId)
        {
            return RedirectToPage("EquipmentStateHistoryPage", equipmentId);
            
        }
    }
}

AikoFrontEnd/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AikoFrontEnd.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AikoFrontEnd/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AikoFrontEnd.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

AikoFrontEnd/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AikoFrontEnd.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

AikoFrontEnd/Pages/Configs.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Configs";
}

<div class="text-center">
    <h1 class="display-4">Configurações</h1>
    <table>
        <thead>
        <th>Nome</th>
        <th>Modelo</th>
        <th>Posição atual</th>
        <th>Estado atual</th>
        </thead>
        <tbody>
            <td>
                
            </td>
        </tbody>
    </table>
</div>

AikoFrontEnd/Pages/EquipmentPositionHistoryPage.cshtml
@page "{equipmentId?}"
@using AikoFrontEnd.Models
@model EquipmentPositionHistoryPage
@{
    ViewData["Title"] = "Equipamentos";
}

<div class="text-center">
    <h1 class="display-4">Current position of equipments</h1>
    <div id='map' style='width: 800px; height: 600px;'></div>
    @if (Model.currentPositions.Count > 0) {
        <script>
            mapboxgl.accessToken = 'pk.eyJ1IjoibGVvbmNvdXRpbmhvMSIsImEiOiJja3k2OXdqbnUwdGU3Mm9wa3V5cjk2dXkwIn0.vJE9hKuPegqvqq4rGVTFrw';
                        
            var map = new mapboxgl.Map({
                container: 'map',
                style: 'mapbox://styles/mapbox/streets-v11',
                center: [-46.00775909423828,-19.15180015563965],
                zoom: 9
            });
            
            @foreach (var pos in Model.currentPositions)
            {
                @:new mapboxgl.Marker()
                @:    .setLngLat([@pos.Lon.ToString().Replace(",", "."), @pos.Lat.ToString().Replace(",", ".")])
                @:    .setPopup(new mapboxgl.Popup().setText("@pos.Equipment.Name em @pos.Date.ToString("g")"))                                                                                                             
                @:    .addTo(map);
            }
        </script>
    }
    
</div>

AikoFrontEnd/Pages/EquipmentStateHistoryPage.cshtml
@page "{equipmentId?}"
@using AikoFrontEnd.Models
@model EquipmentStateHistoryPage
@{
    ViewData["Title"] = "Equipamentos";
}

<div class="text-center">
    <h1 class="display-4">Equipamentos</h1>
    @if(Model.currentStates.Count == 0) {
        <p><em>Atualizando tabela...</em></p>
    } else {
        <table>
            <thead>
            <th>Nome</th>
            <th>Status</th>
            <th>Data do último status</th>
            </thead>
            <tbody>
                @foreach (EquipmentStateHistory hist in Model.currentStates)
                {
                    <form method="post">
                        <tr id=@hist.EquipmentStateId>
                            <td><input type="submit" value=@hist.Equipment.Name asp-page-handler="Equip" asp-route-equipmentId=@hist.EquipmentId /></td>
                            <td>@Model.states.Find(s => s.Id == hist.EquipmentStateId).Name</td>
                            <td>@hist.Date</td>
                        </tr>
                    </form>
                }
            </tbody>
        </table>
    }
    <h1 class="display-4">Estados por equipamento</h1>
        @if(Model.equipmentHistory == null || Model.equipmentHistory.Count == 0 ) {
            <p><em>Clique em uma linha da tabela acima para listar o histórico de estados do equipamento.</em></p>
        } else {
            <table>
                <thead>
                    <th>Nome</th>
                    <th>Status</th>
                    <th>Data</th>
                </thead>
                <tbody>
                    @foreach (EquipmentStateHistory state in Model.equipmentHistory)
                    {
                        <tr style="background-color: @(Model.states.Find(s => s.Id == state.EquipmentStateId).Color + "aa")" >
                            <td>@state.Equipment.Name</td>
                            <td>@Model.states.Find(s => s.Id == state.EquipmentStateId).Name</td>
                            <td>@state.Date</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
</div>

AikoFrontEnd/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AikoFrontEnd/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AikoFrontEnd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">AikoFrontEnd</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/EquipmentStateHistoryPage">EquipmentStateHistory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/EquipmentPositionHistoryPage">EquipmentPositionHistory</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AikoFrontEnd - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>