teste-backend-v2/Models/Equipment.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace teste_backend_v2.Models
{
    public partial class Equipment
    {
        public Guid Id { get; set; }
        public Guid EquipmentModelId { get; set; }
        public string Name { get; set; }

        public virtual EquipmentModel EquipmentModel { get; set; }
    }
}

teste-backend-v2/ViewModels/EquipmentViewModels/DeleteEquipmentViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using teste_backend_v2.Controllers;
using teste_backend_v2.Models;

namespace teste_backend_v2.ViewModels.EquipmentViewModels
{
    public class DeleteEquipmentViewModel
    {
        [Key]
        public Guid? Id { get; set; }

        [Display(Name = "Equipment model")]
        public string EquipmentModelId { get; set; }

        public string Name { get; set; }

        #region Methods

        public JsonResult LoadingData(EquipmentsController controller, AppDbContext db)
        {
            var equipment = db.Equipment.FirstOrDefault(x => x.Id == Id);
            if (equipment == null)
            {
                controller.ModelState.AddModelError(nameof(Name), "Item not found!");
            }

            var equipmentModel = db.EquipmentModels.FirstOrDefault(em => em.Id == equipment.EquipmentModelId);
            if (equipmentModel == null)
            {
                controller.ModelState.AddModelError(nameof(Name), "Item not found!");
            }

            Name = equipment.Name;
            EquipmentModelId = equipmentModel.Name;
            return null;
        }

        #endregion Methods

    }
}

teste-backend-v2/ViewModels/EquipmentViewModels/IncludeEquipmentViewModel.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using teste_backend_v2.Controllers;
using teste_backend_v2.Models;
//using System.Linq;
//using teste_backend_v2.Controllers;

namespace teste_backend_v2.ViewModels.EquipmentViewModels
{
    public class IncludeEquipmentViewModel
    {
        [Required(ErrorMessage = "Required field!")]
        public string Name { get; set; }

        [Display(Name = "Equipment model")]
        [Required(ErrorMessage = "Required field!")]
        public Guid EquipmentModelId { get; set; }

        public IEnumerable<SelectListItem> EquipmentModels { get; set; }

        #region Methods

        public void SetValuesDropdown(AppDbContext db)
        {
            EquipmentModels = db.EquipmentModels.OrderBy(e => e.Name).Select(model => new SelectListItem(model.Name, model.Id.ToString()));
        }

        public JsonResult ValidateData(EquipmentsController controller, AppDbContext db)
        {

            var equipaments = db.Equipment;

            if (equipaments.Any(x => x.Name.ToLower() == Name.ToLower() && x.EquipmentModelId == EquipmentModelId))
            {
                controller.ModelState.AddModelError(nameof(Name), "This item already exists in database!");
            }

            return null;
        }

        #endregion Methods
    }
}

teste-backend-v2/ViewModels/EquipmentViewModels/ListEquipmentViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace teste_backend_v2.ViewModels.EquipmentViewModels
{
    public class ListEquipmentViewModel
    {        
        [Key]
        public Guid Id { get; set; }       

        [Display(Name = "Equipment model")]
        public string EquipmentModelId { get; set; }
               
        public string Name { get; set; }
    }
}

teste-backend-v2/ViewModels/EquipmentViewModels/UpdateEquipmentViewModel.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using teste_backend_v2.Controllers;
using teste_backend_v2.Models;

namespace teste_backend_v2.ViewModels.EquipmentViewModels
{
    public class UpdateEquipmentViewModel
    {
        [Required(ErrorMessage = "Required field!")]
        public string Name { get; set; }

        [Display(Name = "Equipment model")]
        [Required(ErrorMessage = "Required field!")]
        public Guid EquipmentModelId { get; set; }

        public Guid Id { get; set; }

        public IEnumerable<SelectListItem> EquipmentModels { get; set; }

        #region Methods

        public void SetValuesDropdown(AppDbContext db)
        {
            EquipmentModels = db.EquipmentModels.OrderBy(e => e.Name).Select(model => new SelectListItem(model.Name, model.Id.ToString()));
        }

        public JsonResult LoadingData(EquipmentsController controller, AppDbContext db)
        {
            var equipment = db.Equipment.FirstOrDefault(x => x.Id == Id);
            if (equipment == null)
            {
                controller.ModelState.AddModelError(nameof(Name), "Item not found!");
            }

            Name = equipment.Name;
            EquipmentModelId = equipment.EquipmentModelId;
            return null;
        }

        public JsonResult ValidateData(EquipmentsController controller, AppDbContext db)
        {

            var equipment = db.Equipment;

            if (equipment.Any(x => x.Name.ToLower() == Name.ToLower() && x.EquipmentModelId == EquipmentModelId && x.Id != Id))
            {
                controller.ModelState.AddModelError(nameof(Name), "This item already exists in database!");
            }

            return null;
        }

        #endregion Methods
    }
}

teste-backend-v2/Controllers/EquipmentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using teste_backend_v2.Models;
using teste_backend_v2.ViewModels.EquipmentModelViewModels;
using teste_backend_v2.ViewModels.EquipmentPositionViewModels;
using teste_backend_v2.ViewModels.EquipmentStateHistoryViewModels;
using teste_backend_v2.ViewModels.EquipmentStateViewModels;
using teste_backend_v2.ViewModels.EquipmentViewModels;

namespace teste_backend_v2.Controllers
{
    
    public class EquipmentsController : Controller
    {
        protected readonly AppDbContext db;
        private readonly ILogger logger;
        public EquipmentsController(ILogger<EquipmentsController> logger)
        {
            this.logger = logger;
            db = new AppDbContext();            
        }

        #region Equipment Model

        #region List Equipment Model

        [Route("/[controller]/Model/List")]
        public IActionResult ListEquipmentModel()
        {
            var equipmentModels = db.EquipmentModels;
            var listEquipmentModels = equipmentModels.Select(x => new ListEquipmentModelViewModel
            {
                Id = x.Id,
                Name = x.Name
            });

            return View("~/Views/EquipmentModel/ListEquipmentModel.cshtml", listEquipmentModels);
        }

        #endregion List Equipment Model

        #region Include Equipment Model

        [Route("/[controller]/Model/Include")]
        [HttpGet]
        public IActionResult IncludeEquipmentModel()
        {
            IncludeEquipmentModelViewModel model = new IncludeEquipmentModelViewModel();
            return View("~/Views/EquipmentModel/IncludeEquipmentModel.cshtml", model);
        }

        [Route("/[controller]/Model/Include")]
        [HttpPost]
        public IActionResult IncludeEquipmentModel(IncludeEquipmentModelViewModel model)
        {
            
            var error = model.ValidateData(this, db);
            if (error != null) return error;
            if (ModelState.IsValid)
            {
                var guid = Guid.NewGuid();

                using (var transation = db.Database.BeginTransaction())
                {
                    try
                    {
                        EquipmentModel equipmentModel = new EquipmentModel()
                        {
                            Id = guid,
                            Name = model.Name
                        };

                        db.EquipmentModels.Add(equipmentModel);
                        db.SaveChanges();
                        transation.Commit();

                        //return Json(new { success = true, message = "Equipment Model has been included!" });
                        return RedirectToAction(nameof(ListEquipmentModel));
                    }
                    catch (Exception e)
                    {
                        logger.LogError(e, e.Message);
                        return Json(new { success = false });
                    }
                }
            }

            return View("~/Views/EquipmentModel/IncludeEquipmentModel.cshtml", model);
        }

        #endregion Include Equipment Model

        #region Update Equipment Model 

        [Route("/[controller]/Model/Update")]
        [HttpGet]
        public IActionResult UpdateEquipmentModel(Guid id)
        {            
            if (id == null)
            {
                return NotFound();
            }

            UpdateEquipmentModelViewModel model = new UpdateEquipmentModelViewModel();
            model.Id = id;

            var error = model.LoadingData(this, db);
            if (error != null)
            {
                return error;
            }

            return View("~/Views/EquipmentModel/UpdateEquipmentModel.cshtml", model);
        }

        [Route("/[controller]/Model/Update")]
        [HttpPost]
        public IActionResult UpdateEquipmentModel(UpdateEquipmentModelViewModel model)
        {

            var error = model.ValidateData(this, db);
            if (error != null) return error;
            if (ModelState.IsValid)
            {

                using (var transation = db.Database.BeginTransaction())
                {
                    try
                    {
                        var equipmentModel = db.EquipmentModels.FirstOrDefault(x => x.Id == model.Id);
                        equipmentModel.Name = model.Name;

                        db.SaveChanges();
                        transation.Commit();
                        //return Json(new { success = true, message = "Equipment Model has been updated!" });
                        return RedirectToAction(nameof(ListEquipmentModel));
                    }
                    catch (Exception e)
                    {
                        logger.LogError(e, e.Message);
                        return Json(new { success = false });
                    }
                }
            }

            return View("~/Views/EquipmentModel/UpdateEquipmentModel.cshtml", model);
        }

        #endregion Update Equipment Model 

        #region Delete Equipment Model

        [Route("[controller]/Model/Delete")]
        [HttpGet]
        public async Task<IActionResult> DeleteEquipmentModel(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
        
            var equipmentModel = await db.EquipmentModels.FirstOrDefaultAsync(m => m.Id == id);
            if (equipmentModel == null)
            {
                return NotFound();
            }
            return View("~/Views/EquipmentModel/DeleteEquipmentModel.cshtml", equipmentModel);           
        }

        [Route("[controller]/Model/Delete")]
        [HttpPost]
        public IActionResult DeleteEquipmentModel(Guid id)
        {

            using (var transation = db.Database.BeginTransaction())
            {
                try
                {
                    var equipmentModel = db.EquipmentModels.FirstOrDefault(x => x.Id == id);
                    db.EquipmentModels.Remove(equipmentModel);
                    db.SaveChanges();
                    transation.Commit();
                    //return Json(new { success = true, message = "Equipment Model has been deleted!" });
                    return RedirectToAction(nameof(ListEquipmentModel));
                }
                catch (Exception e)
                {
                    logger.LogError(e, e.Message);
                    return Json(new { success = false });
                }
            }
        }

        #endregion Delete Equipment Model

        #endregion Equipment Model

        #region Equipments States

        #region List Equipments States

        [Route("/[controller]/State/List")]
        public IActionResult ListEquipmentState()
        {
            var equipmentStates = db.EquipmentStates;
            var listEquipmentStates = equipmentStates.Select(x => new ListEquipmentStateViewModel
            {
                Id = x.Id,
                Name = x.Name,
                Color = x.Color
            });

            return View("~/Views/EquipmentState/ListEquipmentState.cshtml", listEquipmentStates);
        }

        #endregion List Equipments States

        #region Include Equipment State

        [Route("/[controller]/State/Include")]
        [HttpGet]
        public IActionResult IncludeEquipmentState()
        {
            IncludeEquipmentStateViewModel model = new IncludeEquipmentStateViewModel();
            return View("~/Views/EquipmentState/IncludeEquipmentState.cshtml", model);
        }

        [Route("/[controller]/State/Include")]
        [HttpPost]
        public IActionResult IncludeEquipmentState(IncludeEquipmentStateViewModel model)
        {

            var error = model.ValidateData(this, db);
            if (error != null) return error;
            if (ModelState.IsValid)
            {
                var guid = Guid.NewGuid();

                using (var transation = db.Database.BeginTransaction())
                {
                    try
                    {
                        EquipmentState equipmentsState = new EquipmentState()
                        {
                            Id = guid,
                            Name = model.Name,
                            Color = model.Color
                        };

                        db.EquipmentStates.Add(equipmentsState);
                        db.SaveChanges();
                        transation.Commit();

                        //return Json(new { success = true, message = "Equipment State has been included!" });
                        return RedirectToAction(nameof(ListEquipmentState));
                    }
                    catch (Exception e)
                    {
                        logger.LogError(e, e.Message);
                        return Json(new { success = false });
                    }
                }
            }

            return View("~/Views/EquipmentState/IncludeEquipmentState.cshtml", model);
        }

        #endregion Include Equipment State

        #region Update Equipment State

        [Route("/[controller]/State/Update")]
        [HttpGet]
        public IActionResult UpdateEquipmentState(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            UpdateEquipmentStateViewModel model = new UpdateEquipmentStateViewModel();
            model.Id = id;

            var error = model.LoadingData(this, db);
            if (error != null)
            {
                return error;
            }

            return View("~/Views/EquipmentState/UpdateEquipmentState.cshtml", model);
        }

        [Route("/[controller]/State/Update")]
        [HttpPost]

teste-backend-v2/Views/Equipment/DeleteEquipment.cshtml
@model teste_backend_v2.ViewModels.EquipmentViewModels.DeleteEquipmentViewModel
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Equipment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EquipmentModelId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EquipmentModelId)
        </dd>
    </dl>
    
    <form asp-action="DeleteEquipment">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("ListEquipment", "Equipments")'">Back to list</button>        
    </form>
</div>

teste-backend-v2/Views/Equipment/IncludeEquipment.cshtml
@model teste_backend_v2.ViewModels.EquipmentViewModels.IncludeEquipmentViewModel

@{
    ViewData["Title"] = "Include";
}

<h1>Include</h1>

<h4>Equipment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="IncludeEquipment">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label" style="width: 100%;"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group" style="margin-top: 5px;">
                <label asp-for="EquipmentModelId" class="control-label col col-sm-3 required" style="width: 100%;"></label>
                <div class="col col-sm-7">
                    <select asp-for="EquipmentModelId" asp-items="@Model.EquipmentModels" class="form-select">
                        <option value="">Select an item</option>
                    </select>
                    <span asp-validation-for="EquipmentModelId" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group" style="margin-top: 10px;">
                <input type="submit" value="Include" class="btn btn-primary" /> |
                <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("ListEquipment", "Equipments")'">Back to list</button> 
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

teste-backend-v2/Views/Equipment/ListEquipment.cshtml
@model IEnumerable<teste_backend_v2.ViewModels.EquipmentViewModels.ListEquipmentViewModel>

@{
    ViewData["Title"] = "Equipment";
}

<h1>Equipments</h1>

<div class="form-group">
    <button class="btn btn-primary" onclick="location.href='@Url.Action("IncludeEquipment", "Equipments")'">Include</button>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EquipmentModelId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EquipmentModelId)
            </td>
            <td>
                <a asp-action="UpdateEquipment" asp-route-id="@item.Id">Edit</a> |                
                <a asp-action="DeleteEquipment" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

teste-backend-v2/Views/Equipment/UpdateEquipment.cshtml
@model teste_backend_v2.ViewModels.EquipmentViewModels.UpdateEquipmentViewModel

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>Equipment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateEquipment">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label" style="width: 100%;"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

             <div class="form-group" style="margin-top: 5px;">
                <label asp-for="EquipmentModelId" class="control-label col col-sm-3 required" style="width: 100%;"></label>
                <div class="col col-sm-7">
                    <select asp-for="EquipmentModelId" asp-items="@Model.EquipmentModels" class="form-select">
                        <option value="">Select an item</option>
                    </select>
                    <span asp-validation-for="EquipmentModelId" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group"  style="margin-top: 10px;">
                <input type="submit" value="Save" class="btn btn-primary" /> |
                <button type="button" class="btn btn-secondary" onclick="location.href='@Url.Action("ListEquipment", "Equipments")'">Back to list</button> 
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}